sudo: false
language: node_js
node_js:
  - "6.2"
cache:
  directories:
    - node_modules
    - .eslintcache
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
      
