'use strict';

exports.BattlePokedex = {
	pyukumuku: {
		inherit: true,
		species: "Pyukumuku",
		digimon: "Botamon",
		types: ["Fire"],
		baseStats: {
			hp: 66,
			atk: 47,
			def: 32,
			spa: 47,
			spd: 32,
			spe: 29,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 2.3,
		color: "Black",
		evos: ["Koromon", "Sukamon"],
	},
	vanillite: {
		inherit: true,
		species: "Vanillite",
		digimon: "Poyomon",
		types: ["Air"],
		baseStats: {
			hp: 70,
			atk: 37,
			def: 38,
			spa: 37,
			spd: 38,
			spe: 26,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 2.3,
		color: "White",
		evos: ["Tokomon", "Sukamon"],
	},
	darumaka: {
		inherit: true,
		species: "Darumaka",
		digimon: "Punimon",
		types: ["Air"],
		baseStats: {
			hp: 64,
			atk: 51,
			def: 30,
			spa: 51,
			spd: 30,
			spe: 38,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 2.3,
		color: "Red",
		evos: ["Tsunomon", "Sukamon"],
	},
	cascoon: {
		inherit: true,
		species: "Cascoon",
		digimon: "Yuramon",
		types: ["Earth"],
		baseStats: {
			hp: 69,
			atk: 24,
			def: 36,
			spa: 24,
			spd: 36,
			spe: 19,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 2.3,
		color: "White",
		evos: ["Tanemon", "Sukamon"],
	},
	//In-Training/
	igglybuff: {
		inherit: true,
		species: "Igglybuff",
		digimon: "Koromon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 66,
			atk: 47,
			def: 35,
			spa: 47,
			spd: 35,
			spe: 28,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 4.5,
		color: "Pink",
		evos: ["Agumon", "Gabumon", "Kunemon", "Sukamon"],
		prevo: ["Botamon"],
	},
	swirlix: {
		inherit: true,
		species: "Swirlix",
		digimon: "Tokomon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 60,
			atk: 36,
			def: 29,
			spa: 36,
			spd: 29,
			spe: 38,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 4.5,
		color: "White",
		evos: ["Patamon", "Biyomon", "Kunemon", "Sukamon"],
		prevos: ["Poyomon"],
	},
	swinub: {
		inherit: true,
		species: "Swinub",
		digimon: "Tsunomon",
		types: ["Air", "Ice"],
		baseStats: {
			hp: 64,
			atk: 51,
			def: 33,
			spa: 51,
			spd: 33,
			spe: 37,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 4.5,
		color: "Brown",
		evos: ["Elecmon", "Penguinmon", "Kunemon", "Sukamon"],
		prevos: ["Punimon"],
	},
	sunkern: {
		inherit: true,
		species: "Sunkern",
		digimon: "Tanemon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 63,
			atk: 38,
			def: 31,
			spa: 38,
			spd: 31,
			spe: 30,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 4.5,
		color: "Green",
		evos: ["Palmon", "Betamon", "Kunemon", "Sukamon"],
		prevos: ["Yuramon"],
	},
	//Rookie/
	helioptile: {
		inherit: true,
		species: "Helioptile",
		digimon: "Agumon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 111,
			atk: 83,
			def: 62,
			spa: 83,
			spd: 62,
			spe: 57,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 6.8,
		color: "Yellow",
		evo: ["Birdramon", "Centarumon", "Greymon", "Meramon", "Monochromon", "Tyrannomon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Koromon"],
	},
	rockruff: {
		inherit: true,
		species: "Rockruff",
		digimon: "Gabumon",
		types: ["Battle", "Fire"],
		baseStats: {
			hp: 113,
			atk: 86,
			def: 59,
			spa: 86,
			spd: 59,
			spe: 63,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 6.8,
		color: "White",
		evo: ["Centarumon", "Drimogemon", "Garurumon", "Monochromon", "Ogremon", "Tyrannomon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Koromon"],
	},
	dedenne: {
		inherit: true,
		species: "Dedenne",
		digimon: "Patamon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 96,
			atk: 69,
			def: 56,
			spa: 69,
			spd: 56,
			spe: 76,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 6.8,
		color: "Brown",
		evo: ["Angemon", "Leomon", "Ogremon", "Unimon", "Ogremon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tokomon"],
	},
	electrike: {
		inherit: true,
		species: "Electrike",
		digimon: "Elecmon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 112,
			atk: 79,
			def: 52,
			spa: 79,
			spd: 52,
			spe: 50,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 6.8,
		color: "Red",
		evo: ["Angemon", "Leomon", "Kokatorimon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tsunomon"],
	},
	oricoriopau: {
		inherit: true,
		species: "Oricorio-Pa'u",
		digimon: "Biyomon",
		types: ["Air", "Fire"],
		baseStats: {
			hp: 99,
			atk: 71,
			def: 53,
			spa: 71,
			spd: 53,
			spe: 73,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 6.8,
		color: "Pink",
		evo: ["Airdramon", "Birdramon", "Kabuterimon", "Kokatorimon", "Unimon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tokomon"],
	},
	weedle: {
		inherit: true,
		species: "Weedle",
		digimon: "Kunemon",
		types: ["Earth", "Air"],
		baseStats: {
			hp: 99,
			atk: 75,
			def: 68,
			spa: 75,
			spd: 68,
			spe: 52,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 6.8,
		color: "Yellow",
		evo: ["Kabuterimon", "Kuwagamon", "Vegiemon"],
		prevo: ["Koromon", "Tokomon", "Tsunomon", "Tanemon", "Sukamon"],
	},
	sunflora: {
		inherit: true,
		species: "Sunflora",
		digimon: "Palmon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 103,
			atk: 74,
			def: 57,
			spa: 74,
			spd: 57,
			spe: 61,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 6.8,
		color: "Green",
		evo: ["Coelamon", "Kuwagamon", "Ninjamon", "Vegiemon", "Whamon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tanemon"],
	},
	mudkip: {
		inherit: true,
		species: "Mudkip",
		digimon: "Betamon",
		types: ["Ice", "Air"],
		baseStats: {
			hp: 85,
			atk: 76,
			def: 66,
			spa: 76,
			spd: 66,
			spe: 53,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 6.8,
		color: "Green",
		evo: ["Coelamon", "Drimogemon", "Seadramon", "Shellmon", "Whamon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tanemon"],
	},
	delibird: {
		inherit: true,
		species: "Delibird",
		digimon: "Penguinmon",
		types: ["Ice", "Earth"],
		baseStats: {
			hp: 107,
			atk: 74,
			def: 64,
			spa: 74,
			spd: 64,
			spe: 60,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 6.8,
		color: "Blue",
		evo: ["Fridgimon", "Garurumon", "Mojaymon", "Shellmon", "Whamon", "Nanimon", "Numemon", "Sukamon"],
		prevo: ["Tsunomon"],
	},
	//Champion/
	heliolisk: {
		inherit: true,
		species: "Heliolisk",
		digimon: "Greymon",
		types: ["Fire", "Battle", "Air"],
		baseStats: {
			hp: 170,
			atk: 115,
			def: 92,
			spa: 115,
			spd: 92,
			spe: 80,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 13.6,
		color: "Brown",
		evo: ["MetalGreymon", "SkullGreymon", "Vademon"],
		prevo: ["Agumon"],
	},
	rhyhorn: {
		inherit: true,
		species: "Rhyhorn",
		digimon: "Monochromon",
		types: ["Fire", "Battle", "Earth"],
		baseStats: {
			hp: 170,
			atk: 113,
			def: 99,
			spa: 113,
			spd: 99,
			spe: 73,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 18.1,
		color: "Gray",
		evo: ["MetalGreymon", "MetalMamemon", "Vademon"],
		prevo: ["Agumon", "Gabumon"],
	},
	marowak: {
		inherit: true,
		species: "Marowak",
		digimon: "Ogremon",
		types: ["Battle", "Fire", "Earth"],
		baseStats: {
			hp: 167,
			atk: 116,
			def: 95,
			spa: 116,
			spd: 95,
			spe: 70,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 13.6,
		color: "Green",
		evo: ["Andromon", "Giromon", "Vademon"],
		prevo: ["Gabumon", "Patamon"],
	},
	altaria: {
		inherit: true,
		species: "Altaria",
		digimon: "Airdramon",
		types: ["Air", "Fire"],
		baseStats: {
			hp: 147,
			atk: 85,
			def: 93,
			spa: 85,
			spd: 93,
			spe: 94,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 13.6,
		color: "Blue",
		evo: ["Megadramon", "Phoenixmon", "Vademon"],
		prevo: ["Biyomon"],
	},
	buzzwole: {
		inherit: true,
		species: "Buzzwole",
		digimon: "Kuwagamon",
		types: ["Earth", "Battle", "Air"],
		baseStats: {
			hp: 160,
			atk: 110,
			def: 72,
			spa: 110,
			spd: 72,
			spe: 82,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 13.6,
		color: "Red",
		evo: ["HerculesKabuterimon", "Piximon", "Vademon"],
		prevo: ["Kunemon", "Palmon"],
	},
	beartic: {
		inherit: true,
		species: "Beartic",
		digimon: "Frigimon",
		types: ["Ice", "Battle"],
		baseStats: {
			hp: 155,
			atk: 88,
			def: 102,
			spa: 88,
			spd: 102,
			spe: 67,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 18.1,
		color: "Blue",
		evo: ["Mamemon", "MetalMamemon", "Vademon"],
		prevo: ["Penguinmon"],
	},
	electrode: {
		inherit: true,
		species: "Electrode",
		digimon: "Nanimon",
		types: ["Filth", "Battle"],
		baseStats: {
			hp: 159,
			atk: 106,
			def: 85,
			spa: 106,
			spd: 85,
			spe: 70,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 2.3,
		color: "Brown",
		evo: ["Digitamamon", "Vademon"],
		prevo: ["Agumon", "Betamon", "Biyomon", "Elecmon", "Gabumon", "Kunemon", "Palmon", "Patamon", "Penguinmon"],
	},
	magmar: {
		inherit: true,
		species: "Magmar",
		digimon: "Meramon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 170,
			atk: 120,
			def: 70,
			spa: 120,
			spd: 70,
			spe: 76,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 9.1,
		color: "Red",
		evo: ["Andromon", "MetalGreymon", "Vademon"],
		prevo: ["Agumon"],
	},
	excadrill: {
		inherit: true,
		species: "Excadrill",
		digimon: "Drimogemon",
		types: ["Battle", "Earth"],
		baseStats: {
			hp: 167,
			atk: 109,
			def: 95,
			spa: 109,
			spd: 95,
			spe: 73,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 18.1,
		color: "Purple",
		evo: ["MetalGreymon", "Vademon"],
		prevo: ["Betamon", "Gabumon"],
	},
	pyroar: {
		inherit: true,
		species: "Pyroar",
		digimon: "Leomon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 168,
			atk: 118,
			def: 78,
			spa: 118,
			spd: 78,
			spe: 75,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 9.1,
		color: "Yellow",
		evo: ["Andromon", "Mamemon", "Vademon"],
		prevo: ["Elecmon", "Patamon"],
	},
	combusken: {
		inherit: true,
		species: "Combusken",
		digimon: "Kokatorimon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 159,
			atk: 101,
			def: 76,
			spa: 101,
			spd: 76,
			spe: 80,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 13.6,
		color: "White",
		evo: ["Andromon", "Mamemon", "Vademon"],
		prevo: ["Elecmon", "Patamon"],
	},
	carnivine: {
		inherit: true,
		species: "Carnivine",
		digimon: "Vegiemon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 152,
			atk: 82,
			def: 93,
			spa: 82,
			spd: 93,
			spe: 73,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 4.5,
		color: "Green",
		evo: ["Piximon", "Vademon"],
		prevo: ["Kunemon", "Palmon"],
	},
	crustle: {
		inherit: true,
		species: "Crustle",
		digimon: "Shellmon",
		types: ["Ice", "Earth"],
		baseStats: {
			hp: 171,
			atk: 103,
			def: 102,
			spa: 103,
			spd: 102,
			spe: 63,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 18.1,
		color: "Pink",
		evo: ["MegaSeadramon", "HerculesKabuterimon", "Vademon"],
		prevo: ["Betamon", "Pengiunmon"],
	},
	vigoroth: {
		inherit: true,
		species: "Vigoroth",
		digimon: "Mojyamon",
		types: ["Ice", "Battle", "Earth"],
		baseStats: {
			hp: 157,
			atk: 94,
			def: 102,
			spa: 94,
			spd: 102,
			spe: 67,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 9.1,
		color: "White",
		evo: ["Mamemon", "SkullGreymon", "Vademon"],
		prevo: ["Penguinmon"],
	},
	moltres: {
		inherit: true,
		species: "Moltres",
		digimon: "Birdramon",
		types: ["Fire", "Air"],
		baseStats: {
			hp: 149,
			atk: 92,
			def: 75,
			spa: 92,
			spd: 75,
			spe: 90,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 9.1,
		color: "Red",
		evo: ["Phoenixmon", "Vademon"],
		prevo: ["Agumon", "Biyomon"],
	},
	tyrantrum: {
		inherit: true,
		species: "Tyrantrum",
		digimon: "Tyrannomon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 168,
			atk: 112,
			def: 78,
			spa: 112,
			spd: 78,
			spe: 75,
		},
		abilities: {
			0: "Data",
		},
		color: "Red",
		weightkg: 13.6,
		prevo: ["Agumon", "Gabumon", "Patamon"],
		evo: ["MetalGreymon", "Megadramon", "Vademon"],
	},
	togetic: {
		inherit: true,
		species: "Togetic",
		digimon: "Angemon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 150,
			atk: 95,
			def: 77,
			spa: 95,
			spd: 77,
			spe: 88,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 9.1,
		color: "White",
		prevo: ["Elecmon", "Patamon"],
		evo: ["Andromon", "Devimon", "Phoenixmon", "Vademon"],
	},
	rapidash: {
		inherit: true,
		species: "Rapidash",
		digimon: "Unimon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 149,
			atk: 96,
			def: 75,
			spa: 96,
			spd: 75,
			spe: 87,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 13.6,
		color: "White",
		prevo: ["Biyomon", "Patamon"],
		evo: ["Giromon", "Phoenixmon", "Vademon"],
	},
	accelgor: {
		inherit: true,
		species: "Accelgor",
		digimon: "Ninjamon",
		types: ["Earth", "Battle", "Fire"],
		baseStats: {
			hp: 159,
			atk: 107,
			def: 78,
			spa: 107,
			spd: 78,
			spe: 90,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 4.5,
		color: "Red",
		prevo: ["Palmon"],
		evo: ["Mamemon", "Metalmamemon", "Piximon", "Vademon"],
	},
	relicanth: {
		inherit: true,
		species: "Relicanth",
		digimon: "Coelamon",
		types: ["Ice", "Earth"],
		baseStats: {
			hp: 164,
			atk: 89,
			def: 87,
			spa: 89,
			spd: 87,
			spe: 81,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 13.6,
		color: "White",
		prevo: ["Betamon", "Palmon"],
		evo: ["MegaSeadramon", "Vademon"],
	},
	mukalola: {
		inherit: true,
		species: "Muk-Alola",
		digimon: "Numemon",
		types: ["Filth"],
		baseStats: {
			hp: 143,
			atk: 82,
			def: 97,
			spa: 82,
			spd: 97,
			spe: 69,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 2.3,
		color: "Green",
		prevo: ["Agumon", "Betamon", "Biyomon", "Elecmon", "Gabumon", "Kunemon", "Palmon", "Patamon", "Penguinmon"],
		evo: ["Monzemon", "Vademon"],
	},
	mudsdale: {
		inherit: true,
		species: "Mudsdale",
		digimon: "Centarumon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 151,
			atk: 96,
			def: 97,
			spa: 96,
			spd: 97,
			spe: 88,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 13.6,
		color: "Brown",
		prevo: ["Agumon", "Gabumon"],
		evo: ["Andromon", "Giromon", "Vademon"],
	},
	banette: {
		inherit: true,
		species: "Banette",
		digimon: "Devimon",
		types: ["Battle", "Air", "Ice"],
		baseStats: {
			hp: 166,
			atk: 108,
			def: 82,
			spa: 108,
			spd: 82,
			spe: 79,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 9.1,
		color: "Black",
		prevo: ["Angemon"],
		evo: ["Megadramon", "SkullGreymon", "Vademon"],
	},
	mimikyu: {
		inherit: true,
		species: "Mimikyu",
		digimon: "Bakemon",
		types: ["Air", "Ice"],
		baseStats: {
			hp: 156,
			atk: 86,
			def: 93,
			spa: 86,
			spd: 93,
			spe: 84,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 9.1,
		color: "White",
		prevo: ["Agumon", "Betamon", "Biyomon", "Elecmon", "Gabumon", "Kunemon", "Palmon", "Patamon", "Penguinmon"],
		evo: ["SkullGreymon", "Giromon", "Vademon"],
	},
	heracross: {
		inherit: true,
		species: "Heracross",
		digimon: "Kabuterimon",
		types: ["Earth", "Fire", "Air"],
		baseStats: {
			hp: 168,
			atk: 106,
			def: 102,
			spa: 106,
			spd: 102,
			spe: 81,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 13.6,
		color: "Blue",
		prevo: ["Biyomon", "Kunemon"],
		evo: ["HerculesKabuterimon", "MetalMamemon", "Vademon"],
	},
	dragonair: {
		inherit: true,
		species: "Dragonair",
		digimon: "Seadramon",
		types: ["Ice", "Earth", "Fire"],
		baseStats: {
			hp: 151,
			atk: 105,
			def: 94,
			spa: 105,
			spd: 94,
			spe: 73,
		},
		abilities: {
			0: "Data",
		},
		weightkg: 13.6,
		color: "Blue",
		prevo: ["Betamon"],
		evo: ["MegaSeadramon", "Megadramon", "Vademon"],
	},
	lycanroc: {
		inherit: true,
		species: "Lycanroc",
		digimon: "Garurumon",
		types: ["Ice", "Fire", "Battle"],
		baseStats: {
			hp: 166,
			atk: 101,
			def: 80,
			spa: 101,
			spd: 80,
			spe: 83,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 13.6,
		color: "White",
		prevo: ["Gabumon", "Penguinmon"],
		evo: ["MegaSeadramon", "SkullGreymon", "Vademon"],
	},
	garbodor: {
		inherit: true,
		species: "Garbodor",
		digimon: "Sukamon",
		types: ["Filth"],
		baseStats: {
			hp: 158,
			atk: 84,
			def: 88,
			spa: 84,
			spd: 88,
			spe: 77,
		},
		abilities: {
			0: "Virus",
		},
		weightkg: 2.3,
		color: "Yellow",
		prevo: ["Agumon", "Betamon", "Biyomon", "Elecmon", "Gabumon", "Kunemon", "Palmon", "Patamon", "Penguinmon"],
		evo: ["Etemon", "Vademon"],
	},
	//Ultimate/
	druddigon: {
		inherit: true,
		species: "Druddigon",
		digimon: "MetalGreymon",
		types: ["Mech", "Fire", "Battle"],
		baseStats: {
			hp: 220,
			atk: 136,
			def: 117,
			spa: 136,
			spd: 117,
			spe: 102,
		},
		abilities: {
			0: "Virus",
		},
		color: "Purple",
		weightkg: 22.7,
		prevos: ["Greymon", "Monochromon"],
	},
	aggron: {
		inherit: true,
		species: "Aggron",
		digimon: "SkullGreymon",
		types: ["Battle", "Ice", "Mech"],
		baseStats: {
			hp: 236,
			atk: 146,
			def: 125,
			spa: 146,
			spd: 125,
			spe: 89,
		},
		abilities: {
			0: "Virus",
		},
		color: "White",
		weightkg: 13.6,
		prevos: ["Bakemon", "Devimon", "Garurumon", "Greymon", "Mojyamon"],
	},
	pawniard: {
		inherit: true,
		species: "Pawniard",
		digimon: "Giromon",
		types: ["Mech", "Air", "Battle"],
		baseStats: {
			hp: 214,
			atk: 139,
			def: 103,
			spa: 139,
			spd: 103,
			spe: 97,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "Purple",
		weightkg: 2.3,
		prevos: ["Bakemon", "Centarumon", "Ogremon", "Unimon"],
	},
	pinsirmega: {
		inherit: true,
		species: "Pinsir-Mega",
		digimon: "HerculesKabuterimon",
		types: ["Earth", "Battle", "Fire"],
		baseStats: {
			hp: 322,
			atk: 178,
			def: 156,
			spa: 178,
			spd: 156,
			spe: 77,
		},
		abilities: {
			0: "Data",
		},
		color: "Yellow",
		weightkg: 18.1,
		prevos: ["Kabuterimon", "Kuwagamon", "Shellmon"],
	},
	chingling: {
		inherit: true,
		species: "Chingling",
		digimon: "Mamemon",
		types: ["Battle", "Mech"],
		baseStats: {
			hp: 218,
			atk: 128,
			def: 117,
			spa: 128,
			spd: 117,
			spe: 102,
		},
		abilities: {
			0: "Data",
		},
		color: "Gray",
		weightkg: 2.3,
		prevos: ["Frigimon", "Leomon", "Mojyamon", "Ninjamon", "Whamon"],
	},
	gyarados: {
		inherit: true,
		species: "Gyarados",
		digimon: "MegaSeadramon",
		types: ["Ice", "Air"],
		baseStats: {
			hp: 225,
			atk: 129,
			def: 105,
			spa: 129,
			spd: 105,
			spe: 104,
		},
		abilities: {
			0: "Data",
		},
		color: "Red",
		weightkg: 13.6,
		prevos: ["Coelamon", "Garurumon", "Seadramon", "Shellmon", "Whamon"],
	},
	beheeyem: {
		inherit: true,
		species: "Beheeyem",
		digimon: "Vademon",
		types: ["Mech", "Earth"],
		baseStats: {
			hp: 204,
			atk: 134,
			def: 119,
			spa: 134,
			spd: 119,
			spe: 92,
		},
		abilities: {
			0: "Virus",
		},
		color: "Pink",
		weightkg: 2.3,
		prevos: ["Airdramon", "Angemon", "Bakemon", "Birdramon", "Centarumon", "Coelamon", "Devimon", "Drimogemon", "Frigimon", "Garurumon", "Greymon", "Kabuterimon", "Kokatorimon", "Kuwagamon", "Leomon", "Meramon", "Mojyamon", "Monochromon", "Nanimon", "Numemon", "Ogremon", "Seadramon", "Shellmon", "Sukamon", "Tyrannomon", "Unimon", "Vegiemon", "Whamon"],
	},
	simisear: {
		inherit: true,
		species: "Simisear",
		digimon: "Etemon",
		types: ["Battle", "Air", "Filth"],
		baseStats: {
			hp: 204,
			atk: 116,
			def: 125,
			spa: 116,
			spd: 125,
			spe: 92,
		},
		abilities: {
			0: "Virus",
		},
		color: "Brown",
		weightkg: 6.8,
		prevos: ["Sukamon"],
	},
	registeel: {
		inherit: true,
		species: "Registeel",
		digimon: "Andromon",
		types: ["Mech", "Battle", "Air"],
		baseStats: {
			hp: 215,
			atk: 131,
			def: 123,
			spa: 131,
			spd: 123,
			spe: 99,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "Gray",
		weightkg: 18.1,
		prevos: ["Angemon", "Centarumon", "Meramon", "Ogremon"],
	},
	zygarde: {
		inherit: true,
		species: "Zygarde",
		digimon: "Megadramon",
		types: ["Mech", "Ice", "Battle"],
		baseStats: {
			hp: 224,
			atk: 135,
			def: 117,
			spa: 135,
			spd: 117,
			spe: 96,
		},
		abilities: {
			0: "Virus",
		},
		color: "Red",
		weightkg: 24.9,
		prevos: ["Airdramon", "Devimon", "Seadramon", "Tyrannomon"],
	},
	jigglypuff: {
		inherit: true,
		species: "Jigglypuff",
		digimon: "Piximon",
		types: ["Earth", "Air"],
		baseStats: {
			hp: 203,
			atk: 112,
			def: 108,
			spa: 112,
			spd: 108,
			spe: 112,
		},
		abilities: {
			0: "Data",
		},
		color: "Pink",
		weightkg: 2.3,
		prevos: ["Kokatorimon", "Kuwagamon", "Ninjamon", "Vegiemon"],
	},
	ferroseed: {
		inherit: true,
		species: "Ferroseed",
		digimon: "MetalMamemon",
		types: ["Battle", "Mech"],
		baseStats: {
			hp: 211,
			atk: 130,
			def: 119,
			spa: 130,
			spd: 119,
			spe: 106,
		},
		abilities: {
			0: "Data",
		},
		color: "Gray",
		weightkg: 4.6,
		prevos: ["Frigimon", "Kabuterimon", "Monochromon", "Ninjamon"],
	},
	bewear: {
		inherit: true,
		species: "Bewear",
		digimon: "Monzaemon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 230,
			atk: 123,
			def: 122,
			spa: 123,
			spd: 122,
			spe: 90,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "Yellow",
		weightkg: 18.1,
		prevos: ["Numemon"],
	},
	togepi: {
		inherit: true,
		species: "Togepi",
		digimon: "DigiTamamon",
		types: ["Fire", "Air", "Ice"],
		baseStats: {
			hp: 222,
			atk: 119,
			def: 130,
			spa: 119,
			spd: 130,
			spe: 86,
		},
		abilities: {
			0: "Data",
		},
		color: "White",
		weightkg: 4.5,
		prevos: ["Nanimon"],
	},
	wailord: {
		inherit: true,
		species: "Wailord",
		digimon: "Whamon",
		types: ["Ice", "Earth"],
		baseStats: {
			hp: 240,
			atk: 128,
			def: 122,
			spa: 128,
			spd: 122,
			spe: 90,
		},
		abilities: {
			0: "Vaccine",
		},
		weightkg: 18.1,
		color: "Blue",
		evo: ["Mamemon", "MegaSeadramon", "Vademon"],
		prevo: ["Betamon", "Palmon", "Penguinmon"],
	},
	//Mega/
	hooh: {
		inherit: true,
		species: "Ho-Oh",
		digimon: "Phoenixmon",
		types: ["Air", "Fire"],
		baseStats: {
			hp: 325,
			atk: 171,
			def: 141,
			spa: 171,
			spd: 141,
			spe: 141,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "Yellow",
		weightkg: 13.6,
		prevos: ["Aidramon", "Angemon", "Birdramon", "Kokatorimon", "Unimon"],
	},
	genesect: {
		inherit: true,
		species: "Genesect",
		digimon: "Machinedramon",
		types: ["Mech", "Air", "Battle"],
		baseStats: {
			hp: 323,
			atk: 174,
			def: 148,
			spa: 174,
			spd: 148,
			spe: 75,
		},
		abilities: {
			0: "Virus",
		},
		color: "Gray",
		weightkg: 36.3,
	},
	zygarde: {
		inherit: true,
		species: "Zygarde",
		digimon: "*Gigadramon",
		types: ["Mech", "Ice", "Battle"],
		baseStats: {
			hp: 229,
			atk: 139,
			def: 125,
			spa: 139,
			spd: 125,
			spe: 105,
		},
		abilities: {
			0: "Data",
		},
		color: "Gray",
		prevo: ["Airdramon", "Akatorimon", "Birdramon", "Kokatorimon", "Darkizamon", "Flarerizamon", "Guardromon"],
		evo: ["HerculesKabuterimon", "MetalGarurumon", "MetalSeadramon", "Machinedramon", "WarGreymon"],
	},
	ninetailsalola: {
		inherit: true,
		species: "Ninetails-Alola",
		digimon: "*IceLeomon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 223,
			atk: 151,
			def: 103,
			spa: 151,
			spd: 103,
			spe: 99,
		},
		abilities: {
			0: "Data",
		},
		color: "White",
		prevo: ["Garurumon", "Hyougamon", "Ikkakumon", "JungleMojyamon", "Leomon", "Meramon"],
		evo: ["Boltmon", "Magnadramon", "SaberLeomon"],
	},
	simipour: {
		inherit: true,
		species: "Simipour",
		digimon: "*MetalEtemon",
		types: ["Battle", "Air", "Filth"],
		baseStats: {
			hp: 293,
			atk: 145,
			def: 144,
			spa: 145,
			spd: 144,
			spe: 118,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "Silver",
		weightkg: .03,
		prevo: ["Andromon", "Etemon", "Giromon", "MagnaAngemon", "Meteormon", "Monazemon", "WaruMoonzaemon", "WaruSeadramon"],
	},
	golbat: {
		inherit: true,
		species: "Golbat",
		digimon: "*Myotismon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 233,
			atk: 132,
			def: 121,
			spa: 132,
			spd: 121,
			spe: 95,
		},
		abilities: {
			0: "Virus",
		},
		color: "Black",
		weightkg: .018,
		prevo: ["Airdramon", "Angemon", "Bakemon", "Kokatorimon", "Devimon", "Guardromon", "Hyougamon", "IceDevimon", "JungleMojyamon", "Meramon", "Nanimon", "Soulmon"],
		evo: ["VenomMyotismon"],
	},
	yanmega: {
		inherit: true,
		species: "Yanmega",
		digimon: "*Yanmamon",
		types: ["Air"],
		baseStats: {
			hp: 149,
			atk: 104,
			def: 81,
			spa: 104,
			spd: 81,
			spe: 79,
		},
		abilities: {
			0: "Virus",
		},
		color: "Yellow",
		prevo: ["Aruramon", "Dokunemon", "Kunemon", "ModokiBetamon", "Otamanmon", "Tentomon"],
		evo: ["MegaKabuterimon", "Megadramon"],
	},
	geodudealola: {
		inherit: true,
		species: "Geodude-Alola",
		digimon: "*Gotsumon",
		types: ["Battle"],
		baseStats: {
			hp: 131,
			atk: 81,
			def: 80,
			spa: 81,
			spd: 80,
			spe: 48,
		},
		abilities: {
			0: "Data",
		},
		color: "Gray",
		prevo: ["Motimon", "Nyaromon"],
		evo: ["Airdramon", "Darkrizamon", "Garurumon", "Gekomon", "Greymon", "Icemon", "Ninjamon", "Meteormon", "JungleMoyjamon", "Mikemon", "Monochromon", "Ninimon", "Numemon", "Ogremon", "Gatomon", "Tankmon", "MudFrigimon", "Tyranomon"],
	},
	growlithe: {
		inherit: true,
		species: "Growlithe",
		digimon: "*Flarerizamon",
		types: ["Fire"],
		baseStats: {
			hp: 162,
			atk: 111,
			def: 89,
			spa: 111,
			spd: 89,
			spe: 80,
		},
		abilities: {
			0: "Data",
		},
		color: "Red",
		prevo: ["Agumon", "ClearAgumon", "Elecmon", "Goburimon", "Muchomon", "Salamon"],
		evo: ["Gigiadramon", "Megadramon", "SkullGreymon", "Vermillionmon", "Darkizamon"],
	},
	bewear: {
		inherit: true,
		species: "Bewear",
		digimon: "*WaruMonzaemon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 227,
			atk: 123,
			def: 120,
			spa: 123,
			spd: 120,
			spe: 95,
		},
		abilities: {
			0: "Virus",
		},
		color: "Black",
		prevo: ["Bakemon", "BlackGatomon", "Centarumon", "Devimon", "Garurumon", "Guardromon", "Hoyugamon", "JungleMojyamon", "Kabuterimon", "Leomon", "Monzaemon", "Ogremon", "RedVegimon", "Sukamon", "Tyranomon"],
		evo: ["MetalEtemon", "VenomMyotismon", "Machinedramon"],
	},
	bermite: {
		inherit: true,
		species: "Bermite",
		digimon: "*SnowAgumon",
		types: ["Ice", "Battle"],
		baseStats: {
			hp: 98,
			atk: 76,
			def: 66,
			spa: 76,
			spd: 66,
			spe: 54,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "White",
		prevo: ["Nyaromon", "Bukamon"],
		evo: ["Geremon", "Gururumon", "Hyougamon", "Icemon", "Mojyamon", "Seadramon", "ShimaUnimon", "Gatomon", "Frigimon"],
	},
	crabminable: {
		inherit: true,
		species: "Crabominable",
		digimon: "*Hyogamon",
		types: ["Ice", "Battle"],
		baseStats: {
			hp: 164,
			atk: 113,
			def: 92,
			spa: 113,
			spd: 92,
			spe: 72,
		},
		abilities: {
			0: "Virus",
		},
		color: "Blue",
		prevo: ["ClearAgumon", "Elecmon", "Muchomon", "SnowGoburimon", "SnowAgumon"],
		evo: ["BlueMeramon", "Etemon", "Gigadramon", "IceLeomon", "Tekkamon", "Myotismon", "WaruMonzaemon", "Zudomon"],
	},
	garbodor: {
		inherit: true,
		species: "Garbodor",
		digimon: "*PlatinumSukamon",
		types: ["Flith"],
		baseStats: {
			hp: 172,
			atk: 105,
			def: 98,
			spa: 105,
			spd: 98,
			spe: 68,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "White",
		prevo: ["DoKunemon", "Sukamon", "Tsukaimon"],
		evo: ["Etemon", "MetalMamemon", "Myotismon"],
	},
	caterpie: {
		inherit: true,
		species: "Caterpie",
		digimon: "*Dokunemon",
		types: ["Earth", "Air"],
		baseStats: {
			hp: 106,
			atk: 80,
			def: 65,
			spa: 80,
			spd: 65,
			spe: 55,
		},
		abilities: {
			0: "Virus",
		},
		color: "Green",
		prevo: ["Motimon"],
		evo: ["Kokatorimon", "Darkrizamon", "Kuwagamon", "MoriShellmon", "NiseDrimogemon", "PlatinumSukamon", "SandYanmamon", "Togemon", "Yanmamon"],
	},
	rapidash: {
		inherit: true,
		species: "Rapidash",
		digimon: "*ShimaUnimon",
		types: ["Air", "Battle"],
		baseStats: {
			hp: 115,
			atk: 96,
			def: 75,
			spa: 96,
			spd: 75,
			spe: 81,
		},
		abilities: {
			0: "Data",
		},
		color: "White",
		prevo: ["ClearAgumon", "Elecmon", "SnowAgumon"],
		evo: ["Andromon", "SkullGreymon"],
	},
	bastiodon: {
		inherit: true,
		species: "Bastiodon",
		digimon: "*TankMon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 172,
			atk: 112,
			def: 101,
			spa: 112,
			spd: 101,
			spe: 75,
		},
		abilities: {
			0: "Data",
		},
		color: "Green",
		prevo: ["ClearAgumon", "Gotsumon", "Psychemon", "ToyAgumon", "Tsukaimon"],
		evo: ["Andromon", "Gigadramon", "Giromon", "MetalGreymon", "MetalMamemon", "WaruMonzaemon"],
	},
	tangrowth: {
		inherit: true,
		species: "Tangrowth",
		digimon: "*RedVegiemon",
		types: ["Earth", "Fire"],
		baseStats: {
			hp: 159,
			atk: 105,
			def: 81,
			spa: 105,
			spd: 81,
			spe: 76,
		},
		abilities: {
			0: "Virus",
		},
		color: "Red",
		prevo: ["Aruramon", "Elecmon", "Kunemon", "Palmon", "Tentomon"],
		evo: ["MegaKabuterimon", "Lilymon"],
	},
	vigoroth: {
		inherit: true,
		species: "Vigoroth",
		digimon: "*JungleMojyamon",
		types: ["Battle", "Earth"],
		baseStats: {
			hp: 162,
			atk: 105,
			def: 93,
			spa: 105,
			spd: 93,
			spe: 83,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "Brown",
		prevo: ["Gotsumon", "Palmon"],
		evo: ["Etemon", "Meteormon", "IceLeomon", "Myotismon", "WaruMonzaemon"],
	},
	excadrill: {
		inherit: true,
		species: "Excadrill",
		digimon: "*NiseDrigoemon",
		types: ["Battle"],
		baseStats: {
			hp: 163,
			atk: 93,
			def: 92,
			spa: 93,
			spd: 92,
			spe: 76,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Dokunemon", "Gabumon", "ModokiBetamon", "Psychemon"],
		evo: ["Digitamamon", "Meteormon", "Vermilimon"],
	},
	machop: {
		inherit: true,
		species: "Machop",
		digimon: "*Goburimon",
		types: ["Battle"],
		baseStats: {
			hp: 118,
			atk: 82,
			def: 72,
			spa: 82,
			spd: 72,
			spe: 50,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Koromon", "Tanemon", "Tsunomon", "Motimon"],
		evo: ["Airdramon", "Bakemon", "Centalmon", "Coelamon", "Devimon", "Flarerizamon", "Fugamon", "Ninjamon", "Kuwagamon", "Leomon", "Nanimon", "Numemon", "Ogremon", "Tekkamon", "Tyranomon", "Rockmon"],
	},
	ursaring: {
		inherit: true,
		species: "Ursaring",
		digimon: "*MudFrigimon",
		types: ["Battle"],
		baseStats: {
			hp: 152,
			atk: 95,
			def: 99,
			spa: 95,
			spd: 99,
			spe: 66,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Betamon", "Gotsumon", "Psychemon"],
		evo: ["Meteormon", "Tekkamon"],
	},
	rockruff: {
		inherit: true,
		species: "Rockruff",
		digimon: "*Psychemon",
		types: ["Battle"],
		baseStats: {
			hp: 114,
			atk: 86,
			def: 60,
			spa: 86,
			spd: 60,
			spe: 61,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Tsunomon"],
		evo: ["Gururumon", "Mojyamon", "MoriShellmon", "Gatomon", "Tankmon", "Mudfrigimon"],
	},
	mudkip: {
		inherit: true,
		species: "Mudkip",
		digimon: "*ModokiBetamon",
		types: ["Ice", "Air"],
		baseStats: {
			hp: 81,
			atk: 77,
			def: 67,
			spa: 77,
			spd: 67,
			spe: 55,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Betamon"],
		evo: ["Gekomon", "NiseDrimogemon", "Ogremon", "Seadramon", "Shellmon", "Yanmamon"],
	},
	porygon: {
		inherit: true,
		species: "Porygon",
		digimon: "*ToyAgumon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 113,
			atk: 73,
			def: 71,
			spa: 73,
			spd: 71,
			spe: 55,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Koromon"],
		evo: ["ClearAgumon", "Devimon", "Flarerizamon", "Greymon", "Guardromon", "Leomon", "Numemon", "Sukamon", "Gatomon", "Tankmon"],
	},
	togetic: {
		inherit: true,
		species: "Togetic",
		digimon: "*Piddomon",
		types: ["Air"],
		baseStats: {
			hp: 150,
			atk: 95,
			def: 79,
			spa: 95,
			spd: 79,
			spe: 84,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["ClearAgumon", "Patamon", "Biyomon", "Salamon", "Tsukaimon"],
		evo: ["Angewomon", "Giromon", "MagnaAngemon", "Meteormon", "Lilymon", "Monzaemon"],
	},
	gloom: {
		inherit: true,
		species: "Gloom",
		digimon: "*Aruramon",
		types: ["Plant", "Ice"],
		baseStats: {
			hp: 108,
			atk: 73,
			def: 63,
			spa: 73,
			spd: 63,
			spe: 61,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Tanemon"],
		evo: ["Icemon", "IceDevimon", "Ninjamon", "RedVegimon", "Togemon", "Vegimon", "Yanmamon"],
	},
	muk: {
		inherit: true,
		species: "Muk",
		digimon: "*Geremon",
		types: ["Filth"],
		baseStats: {
			hp: 149,
			atk: 93,
			def: 98,
			spa: 93,
			spd: 98,
			spe: 72,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Agumon", "ClearAgumon", "Elecmon", "Gabumon", "Goburimon", "Gomamon", "Gotsumon", "Otamamon", "Palmon", "Patamon", "Biyomon", "Plotmon", "Psychemon", "Shamanmon", "SnowGoburimon", "Tentomon", "ToyAgumon", "Tsukaimon", "SnowAgumon"],
	},
	rhyhorn: {
		inherit: true,
		species: "Rhyhorn",
		digimon: "*Vermilimon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 223,
			atk: 134,
			def: 126,
			spa: 134,
			spd: 126,
			spe: 98,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Flarerizamon", "Monochromon", "MoriShellmon", "NiseDrimogemon"],
		evo: ["BlackWarGreymon", "Machinedramon", "Rosemon"],
	},
	marowakalola: {
		inherit: true,
		species: "Marowak-Alola",
		digimon: "*Fugamon",
		types: ["Air", "Battle", "Fire"],
		baseStats: {
			hp: 168,
			atk: 115,
			def: 86,
			spa: 115,
			spd: 86,
			spe: 78,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Gabumon", "Goburimon", "Palmon", "Biyomon", "Shamanmon"],
		evo: ["Etemon", "WereGarurumon", "BlackWereGarurumon"],
	},
	aron: {
		inherit: true,
		species: "Aron",
		digimon: "*Tekkamon",
		types: ["Mech", "Battle"],
		baseStats: {
			hp: 210,
			atk: 121,
			def: 115,
			spa: 121,
			spd: 115,
			spe: 104,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Goburimon", "Guardromon", "Hyougamon", "Ninjamon", "Nanimon", "Mudfrigimon"],
		evo: ["Boltmon", "HerculesKabuterimon", "HiAndromon", "PrinceMamemon"],
	},
	crustle: {
		inherit: true,
		species: "Crustle",
		digimon: "*MoriShellmon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 165,
			atk: 102,
			def: 100,
			spa: 102,
			spd: 100,
			spe: 68,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Betamon", "Dokunemon", "Palmon", "Psychemon"],
		evo: ["Digitamamon", "Vermilimon"],
	},
	metang: {
		inherit: true,
		species: "Metang",
		digimon: "*Guardromon",
		types: ["Mech", "Battle", "Fire"],
		baseStats: {
			hp: 172,
			atk: 106,
			def: 104,
			spa: 106,
			spd: 104,
			spe: 73,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Betamon", "ClearAgumon", "Muchomon", "Salamon", "Psychemon", "Tentomon", "ToyAgumon"],
		evo: ["Andromon", "Gigadramon", "Megadramon", "MetalMamemon", "Tekkamon", "Vademon", "Myotismon", "WaruMonzaemon"],
	},
	delibird: {
		inherit: true,
		species: "Delibird",
		digimon: "*Muchomon",
		types: ["Earth", "Air"],
		baseStats: {
			hp: 95,
			atk: 70,
			def: 54,
			spa: 70,
			spd: 54,
			spe: 71,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Kuramon"],
		evo: ["Akatorimon", "Flarerizamon", "Guardromon", "Hyougamon", "Ikkakumon", "Ogremon", "Rockmon"],
	},
	glalie: {
		inherit: true,
		species: "Glalie",
		digimon: "*Icemon",
		types: ["Ice", "Battle"],
		baseStats: {
			hp: 159,
			atk: 82,
			def: 103,
			spa: 82,
			spd: 103,
			spe: 74,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Aruraumon", "Gomamon", "Gotsumon", "Salamon", "Shamanmon", "Snow Agumon"],
		evo: ["Etemon", "Meteormon", "Mamemon", "WereGarurumon", "Zudomon"],
	},
	fletchinder: {
		inherit: true,
		species: "Fletchinder",
		digimon: "*Aktorimon",
		types: ["Air", "Ice"],
		baseStats: {
			hp: 158,
			atk: 96,
			def: 93,
			spa: 96,
			spd: 93,
			spe: 80,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Muchomon", "Penguinmon", "Biyomon"],
		evo: ["Garudamon", "Gigadramon"],
	},
	dedenne: {
		inherit: true,
		species: "Dedenne",
		digimon: "*Tsukaimon",
		types: ["Battle", "Air"],
		baseStats: {
			hp: 101,
			atk: 71,
			def: 58,
			spa: 71,
			spd: 58,
			spe: 75,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Tokomon", "Kuramon", "Tsumemon"],
		evo: ["Airdramon", "Bakemon", "BlackGatomon", "Devimon", "IceDevimon", "Ninjamon", "Ogremon", "Piddomon", "PlatinumSukamon", "Saberdramon", "Soulmon", "Tankmon"],
	},
	tyrogue: {
		inherit: true,
		species: "Tyrogue",
		digimon: "*Shamamon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 120,
			atk: 84,
			def: 70,
			spa: 84,
			spd: 70,
			spe: 48,
		},
		abilities: {
			0: "Virus",
		},
		color: "Green",
		prevo: ["Dorimon"],
		evo: ["Bakemon", "Darkrizamon", "Fugamon", "Garurumon", "Icemon", "Ninjamon", "Kuwagamon", "Meramon", "Numemon", "Ogremon"],
	},
	porygon: {
		inherit: true,
		species: "Porygon",
		digimon: "*ClearAgumon",
		types: ["Earth", "Battle"],
		baseStats: {
			hp: 110,
			atk: 73,
			def: 69,
			spa: 73,
			spd: 69,
			spe: 60,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["ToyAgumon", "Bukamon"],
		evo: ["Angemon", "Flarerizamon", "Greymon", "Hyougamon", "IceDevimon", "Ninjamon", "Piddomon", "ShimaUnimon", "Tankmon"],
	},
	carnivine: {
		inherit: true,
		species: "Carnivine",
		digimon: "*Weedmon",
		types: ["Earth"],
		baseStats: {
			hp: 155,
			atk: 103,
			def: 82,
			spa: 103,
			spd: 82,
			spe: 70,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Aruraumon", "Dokunemon", "Elecmon", "ModokiBetamon"],
	},
	banette: {
		inherit: true,
		species: "Banette",
		digimon: "*IceDevimon",
		types: ["Ice", "Battle"],
		baseStats: {
			hp: 161,
			atk: 104,
			def: 90,
			spa: 104,
			spd: 90,
			spe: 75,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Agumon", "Aruraumon", "ClearAgumon", "Patamon", "SnowGoburimon", "Tsukaimon", "SnowAgumon", "DemiDevimon"],
		evo: ["BlueMeramon", "LadyDevimon", "Myotismon", "Zudomon"],
	},
	houndour: {
		inherit: true,
		species: "Houndour",
		digimon: "*Darkizamon",
		types: ["Fire", "Air"],
		baseStats: {
			hp: 160,
			atk: 113,
			def: 93,
			spa: 113,
			spd: 93,
			spe: 78,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Betamon", "Dokunemon", "Flarerizamon", "Gabumon", "Gotsumon", "Shamanmon"],
		evo: ["Beastmon", "Gigadramon"],
	},
	yanmega: {
		inherit: true,
		species: "Yanmega",
		digimon: "*SandYanmamon",
		types: ["Air", "Fire"],
		baseStats: {
			hp: 156,
			atk: 92,
			def: 104,
			spa: 92,
			spd: 104,
			spe: 76,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Betamon", "Dokunemon"],
		evo: ["Gigadramon", "ShogunGekomon"],
	},
	machop: {
		inherit: true,
		species: "Machop",
		digimon: "*SnowGoburimon",
		types: ["Ice", "Battle"],
		baseStats: {
			hp: 111,
			atk: 79,
			def: 62,
			spa: 79,
			spd: 62,
			spe: 61,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Bukamon"],
		evo: ["Hyougamon", "IceDevimon", "Ikkakumon", "Monochromon", "Seadramon", "Frigimon"],
	},
	emboar: {
		inherit: true,
		species: "Emboar",
		digimon: "*BlueMeramon",
		types: ["Ice", "Fire"],
		baseStats: {
			hp: 235,
			atk: 132,
			def: 98,
			spa: 132,
			spd: 98,
			spe: 106,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Angemon", "Bakemon", "Devimon", "Gururumon", "Hyougamon", "IceDevimon", "Meramon"],
		evo: ["Boltmon", "Devitamamon", "Rosemon"],
	},
	lycanroc: {
		inherit: true,
		species: "lycanroc",
		digimon: "*Gururumon",
		types: ["Battle", "Ice"],
		baseStats: {
			hp: 166,
			atk: 101,
			def: 78,
			spa: 101,
			spd: 78,
			spe: 85,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Gabumon", "Psychemon", "SnowAgumon"],
		evo: ["BlueMeramon", "WereGarurumon", "BlackWereGarurumon"],
	},
	moltres: {
		inherit: true,
		species: "Moltres",
		digimon: "*Saberdramon",
		types: ["Ice", "Air"],
		baseStats: {
			hp: 148,
			atk: 94,
			def: 72,
			spa: 94,
			spd: 72,
			spe: 90,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Pengunmon", "Biyomon", "Tsukaimon", "DemiDevimon"],
		evo: ["Garudamon", "LadyDevimon", "Megadramon", "WaruSeadramon"],
	},
	mimikyu: {
		inherit: true,
		species: "Mimikyu",
		digimon: "*Soulmon",
		types: ["Air", "Ice"],
		baseStats: {
			hp: 156,
			atk: 90,
			def: 93,
			spa: 90,
			spd: 93,
			spe: 80,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Tsukaimon", "DemiDevimon"],
		evo: ["LadyDevimon", "MetalGreymon", "Myotismon"],
	},
	ursaring: {
		inherit: true,
		species: "Ursaring",
		digimon: "*Rockmon",
		types: ["Ice", "Battle"],
		baseStats: {
			hp: 160,
			atk: 75,
			def: 63,
			spa: 75,
			spd: 63,
			spe: 53,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Agumon", "Goburimon", "Muchomon", "Biyomon", "Salamon"],
		evo: ["Meteormon", "LadyDevimon", "MetalGreymon", "Zudomon"],
	},
	shellder: {
		inherit: true,
		species: "Shellder",
		digimon: "*Otamamon",
		types: ["Ice"],
		baseStats: {
			hp: 105,
			atk: 75,
			def: 63,
			spa: 75,
			spd: 63,
			spe: 53,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Motimon", "Bukamon"],
		evo: ["Coelamon", "Gekomon", "Geremon", "Kuwagamon", "Mojyamon", "Numemon", "Seadramon", "Shellmon", "Gatomon", "Whamon", "Yanmamon"],
	},
	froakie: {
		inherit: true,
		species: "Froakie",
		digimon: "*Gekomon",
		types: ["Ice"],
		baseStats: {
			hp: 149,
			atk: 83,
			def: 84,
			spa: 83,
			spd: 84,
			spe: 80,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Betamon", "Gotsumon", "Modoki", "Otamamon", "Punimon", "Tentomon"],
		evo: ["MegaSeadramon", "Monochromon", "Whamon", "ShogunGekomon"],
	},
	paras: {
		inherit: true,
		species: "Paras",
		digimon: "*Tentomon",
		types: ["Earth"],
		baseStats: {
			hp: 106,
			atk: 75,
			def: 71,
			spa: 75,
			spd: 71,
			spe: 63,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Tokomon", "Motimon"],
		evo: ["Airdramon", "Centarumon", "Gekomon", "Guardromon", "Kabuterimon", "Kuwagamon", "Ogremon", "RedVegimon", "SandYanmamon", "Sukamon", "Gatomon", "Tyranomon", "Yanmamon"],
	},
	gyarados: {
		inherit: true,
		species: "Gyarados",
		digimon: "*WaruSeadramon",
		types: ["Ice", "Air"],
		baseStats: {
			hp: 225,
			atk: 133,
			def: 105,
			spa: 133,
			spd: 105,
			spe: 101,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["BlackWarGreymon", "MetalEtemon", "MetalSeadramon"],
		evo: ["Coelamon", "Nanimon", "Ogremon", "Saberdramon", "Seadramon"],
	},
	golem: {
		inherit: true,
		species: "Golem",
		digimon: "*Meteromon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 231,
			atk: 121,
			def: 129,
			spa: 121,
			spd: 129,
			spe: 108,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Drimogemon", "Rockmon", "Gotsumon", "Icemon", "Leomon", "Nanimon", "NiseDrimogemon", "Piddomon", "PlatinumSukamon", "Mudfrigimon"],
		evo: ["Vermilimon", "Cherubimon (Good)", "Ebemon", "Metaletemon", "MetalGarurumon"],
	},
	aggron: {
		inherit: true,
		species: "Aggron",
		digimon: "*Machinedramon",
		types: ["Mech", "Air", "Battle"],
		baseStats: {
			hp: 323,
			atk: 174,
			def: 148,
			spa: 174,
			spd: 148,
			spe: 124,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Andromon", "Gigadramon", "Megadramon", "MegaSeadramon", "MetalGreymon", "MetalMamemon", "Monzaemon", "SkullGreymon", "Vermilimon", "WaruMonzaemon"],
	},
	heracross: {
		inherit: true,
		species: "Heracross",
		digimon: "*MegaKabuterimon",
		types: ["Air", "Fire", "Battle"],
		baseStats: {
			hp: 238,
			atk: 135,
			def: 121,
			spa: 135,
			spd: 121,
			spe: 94,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Birdramon", "Drimogemon", "Garurumon", "Kabuterimon", "Ogremon", "Sukamon", "Gatomon", "Yanmamon"],
		evo: ["HerculesKabuterimon", "Magnadramon", "WarGreymon"],
	},
	blaziken: {
		inherit: true,
		species: "Blaziken",
		digimon: "*Garudamon",
		types: ["Air", "Fire", "Battle"],
		baseStats: {
			hp: 215,
			atk: 128,
			def: 99,
			spa: 128,
			spd: 99,
			spe: 115,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Airdramon", "Akatorimon", "Angemon", "Birdramon", "Fugamon", "Ikkakumon", "Meramon", "Monochromon", "Saberdramon", "Togemon", "Tyrannomon"],
		evo: ["Phoenixmon", "Magnadramon", "MetalGarurumon", "Seraphimon", "WarGreymon"],
	},
	druddigon: {
		inherit: true,
		species: "Druddigon",
		digimon: "*MetalGreymon",
		types: ["Mech", "Fire", "Battle"],
		baseStats: {
			hp: 222,
			atk: 136,
			def: 117,
			spa: 136,
			spd: 117,
			spe: 100,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Airdramon", "Coelamon", "Devimon", "Drimogemon", "Garurumon", "Greymon", "Leomon", "Numemon", "Tankmon", "Tyrannomon"],
		evo: ["BlackWarGreymon", "MetalEtemon", "MetalGarurumon", "Machinedramon", "WarGreymon"],
	},
	smeargle: {
		inherit: true,
		species: "Smeargle",
		digimon: "*WereGarurumon",
		types: ["Ice", "Fire", "Battle"],
		baseStats: {
			hp: 217,
			atk: 127,
			def: 102,
			spa: 127,
			spd: 102,
			spe: 115,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Fugamon", "Garurumon", "Greymon", "Gururumon", "Icemon", "Ninjamon", "Leomon", "Meramon", "Mojyamon", "Ogremon", "Gatomon", "Tyranomon", "Frigimon"],
		evo: ["Boltmon", "MetalGarurumon", "BlackMetalGarurumon", "MetalSeadramon", "Seraphimon", "Vikemon"],
	},
	zoroark: {
		inherit: true,
		species: "Zoroark",
		digimon: "*BlackWereGarurumon",
		types: ["Ice", "Fire", "Battle"],
		baseStats: {
			hp: 219,
			atk: 130,
			def: 115,
			spa: 130,
			spd: 115,
			spe: 113,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["BlackGatomon", "Fugamon", "Garurumon", "Leomon", "Ogremon"],
		evo: ["BlackMetalGarurumon"],
	},
	haxorus: {
		inherit: true,
		species: "Haxorus",
		digimon: "*WarGreymon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 320,
			atk: 171,
			def: 146,
			spa: 171,
			spd: 146,
			spe: 122,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "",
		prevo: ["Andromon", "MegaKabuterimon", "Garudamon", "Gigadramon", "Giromon", "Greymon", "MagnaAngemon", "Mamemon", "MegaSeadramon", "Megadramon", "MetalGreymon", "SkullGreymon"],
	},
	haxorus: {
		inherit: true,
		species: "Haxorus",
		digimon: "*BlackWarGreymon",
		types: ["Fire", "Battle"],
		baseStats: {
			hp: 322,
			atk: 173,
			def: 139,
			spa: 173,
			spd: 139,
			spe: 127,
		},
		abilities: {
			0: "Virus",
		},
		color: "",
		prevo: ["Megadramon", "MegaSeadramon", "MetalGreymon", "SkullGreymon", "Myotismon", "Vermilimon"],
	},
	mightyena: {
		inherit: true,
		species: "Mightyena",
		digimon: "*MetalGarurumon",
		types: ["Ice", "Mech"],
		baseStats: {
			hp: 312,
			atk: 167,
			def: 121,
			spa: 167,
			spd: 121,
			spe: 131,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Andromon", "Garudamon", "Meteormon", "Megadramon", "MetalGreymon", "Metalmamemon", "Zudomon"],
	},
	mightyena: {
		inherit: true,
		species: "Mightyena",
		digimon: "*BlackMetalGarurumon",
		types: ["Air", "Mech"],
		baseStats: {
			hp: 314,
			atk: 169,
			def: 114,
			spa: 169,
			spd: 114,
			spe: 136,
		},
		abilities: {
			0: "Virus",
		},
		color: "",

		prevo: ["Gigadramon", "LadyDevimon", "Myotismon", "WereGarurumon", "BlackWereGarurumon"],
	},
	florgespink: {
		inherit: true,
		species: "Florgespink",
		digimon: "*Rosemon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 292,
			atk: 153,
			def: 119,
			spa: 153,
			spd: 119,
			spe: 129,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Andromon", "Angewomon", "BlueMeramon", "LadyDevimon", "Lilymon", "Mamemon", "Vermilimon", "Whamon"],
	},
	cacturne: {
		inherit: true,
		species: "Cacturne",
		digimon: "*Togemon",
		types: ["Earth", "Ice", "Battle"],
		baseStats: {
			hp: 166,
			atk: 108,
			def: 96,
			spa: 108,
			spd: 96,
			spe: 71,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Agumon", "Aruraumon", "Dokunemon", "Palmon", "Biyomon", "DemiDevimon"],
		evo: ["Garudamon", "LadyDevimom", "Lilymon", "Mamemon", "IceLeomon", "ShounGekomon"],
	},
	cherrimday: {
		inherit: true,
		species: "Cherrim-Day",
		digimon: "*Lilymon",
		types: ["Earth", "Ice"],
		baseStats: {
			hp: 209,
			atk: 112,
			def: 108,
			spa: 112,
			spd: 108,
			spe: 114,
		},
		abilities: {
			0: "Data",
		},
		color: "",
		prevo: ["Angemon", "Kuwagamon", "Piddomon", "RedVegimon", "Gatomon", "Togemon", "Yanmamon"],
		evo: ["Magnadramon", "Lilithmon", "Rosemon"],
	},
	glameow: {
		inherit: true,
		species: "glameow",
		digimon: "**Gatomon",
		types: ["Battle"],
		baseStats: {
			hp: 151,
			atk: 97,
			def: 76,
			spa: 97,
			spd: 76,
			spe: 85,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "White",
		weightkg: .01, //guess
		prevo: ["Agumon", "Elecmon", "Gabumon", "Otamamon", "Patamon", "Penguinmon", "Salamom", "Psychemon", "Tentomon", "ToyAgumon", "SnowAgumon"],
		evo: ["Angewomon", "MegaKaubterimon", "Beastmon", "MagnaAngemon", "LadyDevimon", "Lilymon", "Mamemon", "MetalMamemon", "Monzaemon", "WereGarurumon"],
	},
	purugly: {
		inherit: true,
		species: "purugly",
		digimon: "**BlackGatomon",
		types: ["Battle"],
		baseStats: {
			hp: 146,
			atk: 99,
			def: 73,
			spa: 99,
			spd: 73,
			spe: 90,
		},
		abilities: {
			0: "Vaccine",
		},
		color: "Black",
		weightkg: 0.01,
		prevo: ["Gabumon", "Patamon", "Salamon", "Gatomon", "Tsukaimon", "DemiDevimon"],
		evo: ["Beastmon", "MagnaAngemon", "LadyDevimon", "WaruMonzaemon", "BlackWereGarurumon"],
	},
};
