'use strict';

exports.BattlePokedex = {
	botamon: {
		num: 1,
		species: "Botamon",
		types: ["Fire"],
		baseStats: {hp: 350, atk: 100, def: 50, spa: 100, spd: 50, spe: 50},
		abilities: {0: "Data"},
		weightkg: 2.3,
		color: "Black",
		evos: ["Koromon"],
	},
    poyomon: {
		num: 2,
		species: "Poyomon",
		types: ["Air"],
		baseStats: {hp: 350, atk: 100, def: 100, spa: 100, spd: 100, spe: 50},
		abilities: {0: "Data"},
		weightkg: 2.3,
		color: "White",
		evos: ["Tokomon"],
	},
	punimon: {
		num: 3,
		species: "Punimon",
		types: ["Air"],
		baseStats: {hp: 350, atk: 50, def: 100, spa: 50, spd: 100, spe: 100},
		abilities: {0: "Data"},
		weightkg: 2.3,
		color: "Red",
		evos: ["Tsunomon"],
	},
	yuramon: {
		num: 4,
		species: "Yuramon",
		types: ["Earth"],
		baseStats: {hp: 550, atk: 50, def: 50, spa: 50, spd: 50, spe: 50},
		abilities: {0: "Data"},
		weightkg: 2.3,
		color: "White",
		evos: ["Tanemon"],
	},
	koromon: {
		num: 5,
		species: "Koromon",
		types: ["Fire", "Battle"],
		baseStats: {hp: 500, atk: 100, def: 50, spa: 100, spd: 50, spe: 50},
		abilities: {0: "Data"},
		weightkg: 4.5,
		color: "Pink",
		evos: ["Agumon", "Gabumon"],
		prevo: ["Botamon"],
	},
    tokomon: {
		num: 6,
		species: "Tokomon",
		types: ["Air", "Battle"],
		baseStats: {hp: 500, atk: 100, def: 100, spa: 100, spd: 100, spe: 50},
		abilities: {0: "Data"},
		weightkg: 4.5,
		color: "White",
		evos: ["Patamon", "Biyomon"],
		prevos: ["Poyomon"],
	},
	tsunomon: {
		num: 7,
		species: "Tsunomon",
		types: ["Air", "Ice"],
		baseStats: {hp: 500, atk: 50, def: 100, spa: 50, spd: 100, spe: 100},
		abilities: {0: "Data"},
		weightkg: 4.5,
		color: "Brown",
		evos: ["Elecmon", "Penguinmon"],
		prevos: ["Punimon"],
	},
	tanemon: {
		num: 8,
		species: "Tanemon",
		types: ["Earth", "Ice"],
		baseStats: {hp: 700, atk: 50, def: 50, spa: 50, spd: 50, spe: 50},
		abilities: {0: "Data"},
		weightkg: 4.5,
		color: "Green",
		evos: ["Palmon", "Betamon"],
		prevos: ["Yuramon"],
	},
};	
